drone:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

#   # Position Controllers ---------------------------------------
#   joint1_position_controller:
#     type: velocity_controllers/JointVelocityController
#     joint: Motor1_cont
#     #pid: {p: 100.0, i: 0.01, d: 10.0}
#     pid: {p: 10000, i: 1, d: 1000}
#   joint2_position_controller:
#     type: velocity_controllers/JointVelocityController
#     joint: Motor2_cont
#     #pid: {p: 100.0, i: 0.01, d: 10.0}
#     pid: {p: 10000, i: 1, d: 1000}
# joint3_position_controller:
#     type: velocity_controllers/JointVelocityController
#     joint: Motor3_cont
#     #pid: {p: 100.0, i: 0.01, d: 10.0}
#     pid: {p: 10000, i: 1, d: 1000}
# joint4_position_controller:
#     type: velocity_controllers/JointVelocityController
#     joint: Motor4_cont
#     #pid: {p: 100.0, i: 0.01, d: 10.0}
#     pid: {p: 10000, i: 1, d: 1000}

#   # effort_controllers/JointPositionController
#   # velocity_controllers/JointGroupVelocityController

  joint_motor_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints: 
            - Motor1_cont
            - Motor2_cont
            - Motor3_cont
            - Motor4_cont

  gazebo_ros_control:
    pid_gains:
      Motor1_cont:
        p: 10000.0
        i: 1.0
        d: 1000.0
        # p: 100.0
        # i: 0.01
        # d: 1000.0
      Motor2_cont:
        p: 10000.0
        i: 1.0
        d: 1000.0
        # p: 100.0
        # i: 0.01
        # d: 1000.0
      Motor3_cont:
        p: 10000.0
        i: 1.0
        d: 1000.0
        # p: 100.0
        # i: 0.01
        # d: 1000.0
      Motor4_cont:
        p: 10000.0
        i: 1.0
        d: 1000.0
        # p: 100.0
        # i: 0.01
        # d: 1000.0